Add parallel tests runner (#179)
* Add parallel-tests script

* Remove duplicate step

* Use matrix name in db url

* Create and migrate before running tests

* Don't create parallel databases

* Remove DATABASE_URL

* Force TCP

* Fix tests when running locally

* Only precompile assets if running system specs

* Precompile assets must happen

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,19 +27,30 @@ jobs:
   test:
     runs-on: ubuntu-latest
     needs: [lint]
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - name: unit
+            rspec_tag: "~type:system"
+          - name: system
+            rspec_tag: "type:system"
     services:
       postgres:
         image: postgres:11-alpine
         ports:
           - "5432:5432"
         env:
-          POSTGRES_DB: stakkd_test
+          POSTGRES_DB: postgres
           POSTGRES_USER: rails
           POSTGRES_PASSWORD: password
     env:
       RAILS_ENV: test
-      DATABASE_URL: "postgres://rails:password@localhost:5432/stakkd_test"
       RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
+      TEST_PGHOST: 127.0.0.1
+      TEST_PGPORT: 5432
+      TEST_PGUSER: rails
+      TEST_PGPASSWORD: password
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
@@ -63,12 +74,14 @@ jobs:
         uses: ruby/setup-ruby@v1
         with:
           bundler-cache: true
-      - name: Set up database schema
-        run: bin/rails db:schema:load
       - name: Precompile assets
         run: bin/rails assets:precompile
       - name: Run tests
-        run: bundle exec rspec || echo "rspec_failed=true" >> $GITHUB_ENV
+        run: |
+          bin/rails db:create db:schema:load db:migrate
+          bundle exec rake parallel:create
+          bundle exec rake parallel:prepare
+          bin/parallel-test --tag "${{ matrix.rspec_tag }}" || echo "rspec_failed=true" >> $GITHUB_ENV
       - name: Upload screenshots on fail
         if: env.rspec_failed == 'true'
         uses: actions/upload-artifact@v7
